"""Matrix definitions and TrialSpec for the automation harness."""

from __future__ import annotations

from dataclasses import dataclass, field
from itertools import product
from pathlib import Path
from typing import List, Optional


REPO_ROOT = Path(__file__).resolve().parents[2]

WAYPOINT_BOUNDS_X = (-100.0, 100.0)
WAYPOINT_BOUNDS_Y = (-100.0, 100.0)
WAYPOINT_BOUNDS_Z = (0.0, 50.0)

OBSTACLE_BOUNDS_X = (-90.0, 90.0)
OBSTACLE_BOUNDS_Y = (-90.0, 90.0)
OBSTACLE_BOUNDS_Z = (5.0, 25.0)

OBS_SIZE_DEFAULT = 5.0
NUM_UAVS_DEFAULT = 3
START_POINTS_DEFAULT = "10,0,10;50,20,10;90,0,10"
SEED_OBSTACLE_OFFSET = 10_000


@dataclass
class TrialSpec:
    trial_id: str
    n_points: int
    n_obstacles: int
    seed: int
    num_uavs: int = NUM_UAVS_DEFAULT
    obs_size: float = OBS_SIZE_DEFAULT
    start_points: str = START_POINTS_DEFAULT
    # When set, skip the random obstacle generator and use this pickle as-is.
    # Used by the smoke matrix for the hand-crafted bug-A scenario.
    obstacles_fixture: Optional[Path] = None
    points_fixture: Optional[Path] = None


def _make_id(prefix: str, n_points: int, n_obstacles: int, seed: int) -> str:
    return f"{prefix}_n{n_points}_o{n_obstacles}_s{seed}"


def matrix_smoke() -> List[TrialSpec]:
    """Stage 0 adversarial smoke matrix: baseline + bug-A overlap fixture + stress.

    Trial 1 (overlap) uses fixtures generated by smoke_overlap.py — the points and
    obstacles are hand-crafted so that iter 1's detour around obstacle A must
    splice through obstacle B, forcing iter 2 to re-detect and resolve it.
    """
    fixtures_dir = Path(__file__).resolve().parent / "fixtures"
    return [
        TrialSpec(
            trial_id=_make_id("smoke", 30, 5, 42),
            n_points=30, n_obstacles=5, seed=42,
        ),
        TrialSpec(
            trial_id="smoke_overlap_bugA",
            n_points=0, n_obstacles=0, seed=11,
            points_fixture=fixtures_dir / "smoke_overlap_points.pkl",
            obstacles_fixture=fixtures_dir / "smoke_overlap_obstacles.pkl",
            obs_size=1.0,  # smaller obstacles for the hand-crafted scenario
        ),
        TrialSpec(
            trial_id=_make_id("smoke", 100, 20, 99),
            n_points=100, n_obstacles=20, seed=99,
        ),
    ]


def matrix_report(seeds: Optional[List[int]] = None) -> List[TrialSpec]:
    """The §4.1 report matrix: 2 waypoint counts x 4 obstacle counts x 10 seeds = 80 trials."""
    if seeds is None:
        seeds = list(range(10))  # 0..9
    waypoint_counts = [30, 100]
    obstacle_counts = [0, 5, 10, 20]
    trials: List[TrialSpec] = []
    for n, m, s in product(waypoint_counts, obstacle_counts, seeds):
        trials.append(TrialSpec(
            trial_id=_make_id("report", n, m, s),
            n_points=n, n_obstacles=m, seed=s,
        ))
    return trials


def matrix_gazebo_subset(seed: int = 0) -> List[TrialSpec]:
    """One seed across the 8 report conditions for Gazebo execution."""
    waypoint_counts = [30, 100]
    obstacle_counts = [0, 5, 10, 20]
    trials: List[TrialSpec] = []
    for n, m in product(waypoint_counts, obstacle_counts):
        trials.append(TrialSpec(
            trial_id=_make_id("gz", n, m, seed),
            n_points=n, n_obstacles=m, seed=seed,
        ))
    return trials


def matrix_gazebo_smoke() -> List[TrialSpec]:
    """Single Gazebo smoke trial — uses the simplest condition (n=30, obs=5)."""
    return [TrialSpec(
        trial_id="gz_smoke_n30_o5_s42",
        n_points=30, n_obstacles=5, seed=42,
    )]


MATRICES = {
    "smoke": matrix_smoke,
    "report": matrix_report,
    "gazebo_subset": matrix_gazebo_subset,
    "gazebo_smoke": matrix_gazebo_smoke,
}


def resolve_matrix(name: str) -> List[TrialSpec]:
    if name not in MATRICES:
        raise ValueError(f"Unknown matrix '{name}'. Choices: {sorted(MATRICES)}")
    return MATRICES[name]()
